### ISSUE TITLE
MotaCoind: main.cpp:2679: bool LoadBlockIndex(bool): Assertion `block.hashMerkleRoot == uint256("")' failed.

### ISSUE THREAD

**Issue by Master-01** [Jahvinci/MotaCoin#7]
Hellow!
After run wallet I get error
`MotaCoind: main.cpp:2679: bool LoadBlockIndex(bool): Assertion `block.hashMerkleRoot == uint256("")' failed.`
How run wallet?

**Comment by Jahvinci** [comment]
Compile instructions: sudo apt-get install git git clone git://
github.com/Jahvinci/MotaCoin.git sudo apt-get install build-essential
libssl-dev libdb++-dev libboost-all-dev libqrencode-dev libminiupnpc-dev
libevent-dev sudo apt-get install qt5-default qt5-qmake qtbase5-dev-tools
qttools5-dev-tools build-essential libboost-dev sudo apt-get
libboost-system-dev libboost-filesystem-dev libboost-program-options-dev
libboost-thread-dev libssl-dev libdb++-devc cd MotaCoin/src/leveldb #Then
create the libleveldb.a and libmemv.a files sh build_detect_platform
build_config.mk ./ cd .. make -f makefile.unix cd .. qmake make then once
done compiling, run with the QT icon in your MotaCoin directory

**Comment by Jahvinci** [comment]
Compile instructions:**

sudo apt-get install git git clone git://github.com/Jahvinci/MotaCoin.git
sudo apt-get install build-essential libssl-dev libdb++-dev
libboost-all-dev libqrencode-dev libminiupnpc-dev libevent-dev sudo apt-get
install qt5-default qt5-qmake qtbase5-dev-tools qttools5-dev-tools
build-essential libboost-dev sudo apt-get install libboost-system-dev
libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev
libssl-dev libdb++-devc cd MotaCoin/src/leveldb #Then create the
libleveldb.a and libmemv.a files sh build_detect_platform build_config.mk
./ cd .. make -f makefile.unix cd .. qmake make then once done compiling,
run with the QT icon in your MotaCoin directory

**Comment by Master-01** [comment]
Program is terminating after start.
debug.log
`MotaCoin version v1.2.0.0 (2018-02-17 21:07:11 -0800)
Using OpenSSL version OpenSSL 1.0.2g  1 Mar 2016
Startup time: 02/19/18 10:42:38
Default data directory /root/.MotaCoin
Used data directory ./_wallet_
dbenv.open LogDir=./_wallet_/database ErrorFile=./_wallet_/db.log
Bound to [::]:50000
Bound to 0.0.0.0:50000
AddLocal(77.66.200.240:50000,6)
Loading block index...
Opening LevelDB in ./_wallet_/txleveldb
Transaction index version is 70508
Opened LevelDB successfully
CBlock(hash=00000dc6c6705f3268e6ca89aa9e6f60018a1f13837ca38e3eaf6212ea06d0ad, ver=1, hashPrevBlock=0000000000000000000000000000000000000000000000000000000000000
000, hashMerkleRoot=4dea911ed96cfc46a3d2502268b87b2184dca77ede5ecd4f069629cfeb52bb59, nTime=1518930490, nBits=1e0fffff, nNonce=172764, vtx=1, vchBlockSig=)
  Coinbase(hash=4dea911ed9, nTime=1518930490, ver=1, vin.size=1, vout.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 00012a4cac44657075747920412e472e20526f6420526f73656e737465696e2073746174656420617420746865204e65777320436f
6e666572656e63653a20e2809c5468657265206973206e6f20616c6c65676174696f6e20696e2074686520696e646963746d656e74207468617420616e7920416d65726963616e207761732061206b6e
6f77696e67207061727469636970616e7420696e207468697320696c6c6567616c2061637469766974792e20)
    CTxOut(empty)
  vMerkleTree: 4dea911ed9
block.GetHash() == 00000dc6c6705f3268e6ca89aa9e6f60018a1f13837ca38e3eaf6212ea06d0ad
block.hashMerkleRoot == 4dea911ed96cfc46a3d2502268b87b2184dca77ede5ecd4f069629cfeb52bb59
block.nTime = 1518930490
block.nNonce = 172764
`
and program closed/terminated
why?

**Comment by Jahvinci** [comment]
This is a bug we know about, should have it fixed within 12 hours.
